if (NOT DEFINED M64P_API_VERSION)
  message(FATAL_ERROR "API version must be set before including this generator")
endif()

if (${M64P_API_VERSION} MATCHES [[^([0-9]|[1-9][0-9]+)\.([0-9]|[1-9][0-9]+)\.([0-9]|[1-9][0-9]+)$]])
  set(M64P_API_VERSION_MAJOR "${CMAKE_MATCH_1}")
  set(M64P_API_VERSION_MINOR "${CMAKE_MATCH_2}")
  set(M64P_API_VERSION_PATCH "${CMAKE_MATCH_3}")
  
elseif(${M64P_API_VERSION} MATCHES [[^([0-9]|[1-9][0-9]+)\.([0-9]|[1-9][0-9]+)$]])
  set(M64P_API_VERSION_MAJOR "${CMAKE_MATCH_1}")
  set(M64P_API_VERSION_MINOR "${CMAKE_MATCH_2}")
  set(M64P_API_VERSION_PATCH 0)
else()
  message(FATAL_ERROR "Invalid version string. Should follow: major.minor(.patch)")
endif()

file(MAKE_DIRECTORY "${PROJECT_BINARY_DIR}/${PROJECT_NAME}_config/")
configure_file("${CMAKE_CURRENT_LIST_DIR}/config.hpp.in" "${PROJECT_BINARY_DIR}/${PROJECT_NAME}_config/config.hpp")
set(CONFIG_DIR "${PROJECT_BINARY_DIR}/${PROJECT_NAME}_config/")